### ISSUE TITLE
Update function error

### ISSUE THREAD

**Issue by gusgeek** [rakibtg/SleekDB#127]
Sorry for being so annoying, but I find that I want to make an update to my database, and it literally updates all the entries with the last update that has been made to that store. 

This is the code snippet

```
$data = $blogUsers->findById($_GET['idUser']);
$data["name"] = $_POST['name'];
$data["level"] = $_POST['level'];
$data["status"] = $_POST['status'];

	if ((isset($_POST['pass'])) && ($_POST['pass'] != "") && ($_POST['pass'] != " ")) { 
		$data["pass"] = password_hash($_POST['pass'], PASSWORD_BCRYPT); 
	}

$results = $blogUsers->update( $data ); 
```

I am doing something wrong?

**Comment by Timu57** [comment]
Hi @gusgeek 
You are not annoying! You can ask as many questions as you want! You are always welcome!

If you want to you can also join our [Discord channel](https://discord.gg/WJGqUFPtZw).

Your code looks completely fine but I thought we could make it a little bit more generic :smiling_face_with_three_hearts: 
It's just an alternative to your code and has nothing to do with your problem, so you can completely ignore it if you want to.
```php
$data = $blogUsers->findById($_GET["idUser"]);
foreach($_POST as $postKey => $postValue){
  if(array_key_exists($postKey, $data) && ( !empty($postValue) || is_string($postValue) && trim($postValue) !== "" ) ){
    $data[$postKey] = ($postKey === "pass") 
      ? password_hash($postValue, PASSWORD_BCRYPT) 
      : $postValue;
  }
}
$results = $blogUsers->update( $data ); 
```

Now to your problem. I am not sure but it could be because you output the $_POST to check if something is updated afterwards?
If so, you will not see any changes because $_POST did not change.
You can very easily find out if that is the problem by checking if you see the updated user after reloading the page.

You could fix that by either using $data to output the changed data or changing the last line of your code snipped to this:
```php
if(false !== $blogUsers->update( $data )){
  $_POST = $data;
}
```

**Comment by gusgeek** [comment]
Hey, thanks! really!

I like what you present to me, although in a way I think I go through the entire _POST array looking for this.

I will take it.

Outside of this, I really couldn't fix the SleekDB Update. I must be very sleepy so tomorrow I will continue and tell you. I close the thread in the meantime.

Thanks again.
