### ISSUE TITLE
Please add Group BY Method

### ISSUE THREAD

**Issue by dvygolov** [rakibtg/SleekDB#129]
Sometimes it is necessary to group your data and it takes time to write grouping manually. Looking forward to have grouping in SleekDB and thank you for this awesome product!

**Comment by Timu57** [comment]
HI @dvygolov,
that could be a nice feature.
I think the implementation is possible but can be a little bit tricky.

# Concept to discuss

https://www.geeksforgeeks.org/sql-group-by/
That article explains Group By in a good way. We can use that to implement Group By correctly.
The Group By functionality should also include the Having functionality instead of extracting it to an extra method.

The Group By method could look like this:

```php
function groupBy(array $groupByFields, string $countKeyName = null, array $select = null, array $having = [])
```

1. Empty fields will not be grouped and excluded
    - Or should we not exclude them? 
2. The result will include all fields specified with $groupByFields by default
3. If $countName is null, no count will be applied to result
4. If select is used every field that is wanted in the result have to be specified.
    - Excepts `SUM`, `MIN`, `MAX` and `AVG` 
5. $having can just be used with fields that are specified with $groupByFields

## $groupByFields
Group result by one or multiple fields. If multiple fields are specified all results that have the same value in all fields that are specified, are grouped together. The specified fields will be added to result by default.

```sql
GROUP BY city, age
```

```php
// Group by city and age
["city", "age"]
```

## $countKeyName
If $countKeyName is not null the amount of documents that are grouped will be applied to the result. The given $countKeyName
will be used as the key.

```sql
SELECT COUNT(*) AS count
```

```php
"count"
```

## $select
If select is used (not null) all fields that are wanted in the result have to be specified.
Previously defined fields are not automatically in the result anymore then.

You can specify all fields that are used to group, the countKeyName and functions.

Available functions: `SUM`, `MIN`, `MAX` and `AVG`

```sql
SELECT
  city, age, count, SUM(follower) AS followerSum, MIN(follower) AS followerMin, MAX(follower) AS followerMax
```

```php
[
  "city",
  "age",
  "count",
  "followerSum" => ["SUM" => "follower"],
  "followerMin" => ["MIN" => "follower"],
  "followerMax" => ["MAX" => "follower"],
]
```

## $having

With the $having you can use the keys that are either specified with $groupByFields, $countName or $select.


```sql
HAVING followerMin > 100 AND followerMax < 7000 AND (city = "london" OR city = "new york")
```

```php
[
  ["followerMin", ">", 100],
  ["followerMax", "<", 7000],
  [
    ["city", "=", "london"],
    "OR",
    ["city", "=", "new york"]
  ]
]
```

## Example use

```sql
SELECT
  city,
  age,
  COUNT(*) AS count,
  age AS maxAge
WHERE
  region = "europe"
GROUP BY
  city, age
HAVING
  count > 100
ORDER BY
  count ASC;
```

```php
$userStore->createQueryBuilder()
  ->where([ "region", "=", "europe" ])
  ->groupBy(
    ["city", "age"],
    "count",
    ["city", "age", "count", "maxAge" => ["MAX" => "age"]],
    [ "count", ">", 100 ] 
  )
  ->orderBy(["count" => "asc"])
  ->getQuery()
  ->fetch();
```

## Lets discuss

If you have ideas or see a problem please do not hesitate to share your thoughts with us!

**Comment by rakibtg** [comment]
@Timu57 
Great follow up on implementing GROUP BY method! 🍻 

Can we extract the code that handles this huge logic into its own class to a different file?

> Empty fields will not be grouped and excluded

We can allow a param like: `ALLOW_EMPTY`; default would be `false`

> The result will include all fields specified with $groupByFields by default

Should we also consider the `select` and `except` method?

**Comment by Timu57** [comment]
@rakibtg 

> Can we extract the code that handles this huge logic into its own class to a different file?

What do you mean with that in detail? I dont quite understand :relaxed: 

> > Empty fields will not be grouped and excluded
> 
> We can allow a param like: `ALLOW_EMPTY`; default would be `false`

That is a really good idea :+1: 

> > The result will include all fields specified with $groupByFields by default
> 
> Should we also consider the `select` and `except` method?

I thought we could disable select and except if groupBy is used. Because `select` and `except` will not have a real effect..

**Comment by rakibtg** [comment]
@Timu57 

> > Can we extract the code that handles this huge logic into its own class to a different file?
>
> What do you mean with that in detail? I dont quite understand ☺️

Sure, I think this is a big feature and it might need lots of code. So, i was thinking if we can move it to a new class and then integrate with our Query class? Would that be a good idea?

**Comment by Timu57** [comment]
@rakibtg 
> Sure, I think this is a big feature and it might need lots of code. So, i was thinking if we can move it to a new class and then integrate with our Query class? Would that be a good idea?

I thought a little bit about that topic but I can not come up with a good idea to split the Query class into multiple smaller classes in an efficient and good way :cry:

**Comment by Timu57** [comment]
# Final implementation

## select()
When using `groupBy` and `select` together the `select` method has additional features.
All fields that are wanted in the result have to be specified.
Previously by default defined fields are not automatically in the result any more.
You can specify all fields that are used to group, the countKeyName and functions.

Available functions: `SUM`, `MIN`, `MAX` and `AVG`

```sql
SELECT
  city AS City, age, count, SUM(follower) AS followerSum, MIN(follower) AS followerMin, MAX(follower) AS followerMax
```

```php
[
  "City" => "city",
  "age",
  "count",
  "followerSum" => ["SUM" => "follower"],
  "followerMin" => ["MIN" => "follower"],
  "followerMax" => ["MAX" => "follower"],
]
```

Example:
```php
$productQueryBuilder
->select( [ "priceSum" => ["sum" => "price"], "Category" => "category.subcategory" ] )
->groupBy([ "category.subcategory" ])
```
Select now also accepts alias for the fields.
PS: You can not use an alias for the $countKeyName specified with `groupBy`, because it is already an alias.

## having()
Having accepts all conditions and the same condition structure like for example `where` and `findBy`.
With the `having` method you can use the keys that are either specified with `groupBy` ($groupByFields and $countName) or `select`.

```php
function having(array $criteria)
```

```sql
HAVING followerMin > 100 AND followerMax < 7000 AND (city = "london" OR city = "new york")
```

```php
[
  ["followerMin", ">", 100],
  ["followerMax", "<", 7000],
  [
    ["city", "=", "london"],
    "OR",
    ["city", "=", "new york"]
  ]
]
```

## groupBy()

```php
function groupBy(array $groupByFields, string $countKeyName = null, bool $allowEmpty = false)
```

1. The result will include all fields specified with $groupByFields by default
2. If $countName is null, no count will be applied to result
3. If $allowEmpty is true, empty results fields will grouped together

### $groupByFields
Group result by one or multiple fields. If multiple fields are specified all results that have the same value in all fields that are specified, are grouped together. The specified fields will be added to result by default.

```sql
GROUP BY city, age
```

```php
// Group by city and age
["city", "age"]
```

### $countKeyName
If $countKeyName is not null the amount of documents that are grouped will be applied to the result. The given $countKeyName
will be used as the key.

```sql
SELECT COUNT(*) AS count
```

```php
"count"
```

## Example use

```sql
SELECT
  city as City,
  age,
  COUNT(*) AS count,
  age AS maxAge
WHERE
  region = "europe"
GROUP BY
  city, age
HAVING
  count > 100
ORDER BY
  count ASC;
```

```php
$userStore->createQueryBuilder()
  ->where([ "region", "=", "europe" ])
  ->select(["City" => "city", "age", "count", "maxAge" => ["MAX" => "age"]])
  ->groupBy(["city", "age"], "count", true)
  ->having([ "count", ">", 100 ] )
  ->orderBy(["count" => "asc"])
  ->getQuery()
  ->fetch();
```

**Comment by Timu57** [comment]
Implemented with version 2.6

**Comment by dvygolov** [comment]
Wow, guys!!! That was FAST, thanks a lot, will give it a try soon🤝

**Comment by Timu57** [comment]
@dvygolov would be nice if you could give us some feedback 😁
