### ISSUE TITLE
delete status

### ISSUE THREAD

**Issue by BLLuis** [rakibtg/SleekDB#48]
Would be cool to return the count of deleted records. I do a fetch before to know the number of records that will be deleted.

**Comment by rakibtg** [comment]
@BLLuis Hi! Can you show an example of how you would like to consume the delete status method in the query?

**Comment by BLLuis** [comment]
Hi, something like this:

$deletedCount = $store->blahblah->delete();
print_r($deletedCount . " registers removed");

Simple as "return the count of deleted records".
Thanks

**Comment by Timu57** [comment]
We could provide this functionality very easy by adding a counter-variable to the delete function and incrementing it with this loop:

https://github.com/rakibtg/SleekDB/blob/9f4c2d95fcb7871955c066dc455a52165d2099dd/src/SleekDB.php#L227

But I am not sure if that is ok, because if we update this function to return a number instead of a boolean value it would not be compatible any more with legacy code.

**Comment by rakibtg** [comment]
@Timu57 I will add an optional parameter:
```php
delete($returnWithCount); // true or false
```
If `$returnWithCount = true` then it will return total amount of items deleted. Or true/false by default.

**Comment by BLLuis** [comment]
Nice.

**Comment by rakibtg** [comment]
Added in [SleekDB 2.0](https://github.com/rakibtg/SleekDB/releases/tag/2.0)!
