### ISSUE TITLE
reuse clause?

### ISSUE THREAD

**Issue by qinst64** [rakibtg/SleekDB#9]
Below is a working clause, which I check existence and update data:
```php
$result = $db->where(...)->...where(...)->fetch();
if(count($result)){
    $db->where(...)->...where(...)->update(...);//working
}
```
Since the __where clause__ are so long and duplicated, my first mind is to rewriting it:
```php
$query = $db->where(...)->...where(...);
$result = $query->fetch();
if(count($result)){
    $query->update(...);//not working, this updates all data
}
```
It is not working as expected. A similar example would be 
 ```php
$query = $db->where(...);
$query->fetch(); //show filtered result by where
$query->fetch(); //run it again, showing all data
```
So, the `fetch()` is actually affecting the `$query` itself, rather than a copy of `$query`. 
I would personally prefer the reuse way would be designed and implemented. Or please telling users do not use it in this way in the tutorial (maybe can save their time). 

BTW, below is a SQL PDO example, which would allow reuse:
```php
$stmt = $db->prepare("select * from data where name=?");

$stmt->execute(["A"]);
$stmt->fetch(PDO::FETCH_ASSOC);//show result where name=="A"

$stmt->execute(["B"]);
$stmt->fetch(PDO::FETCH_ASSOC);//run it again, show result where name=="B"
```

**Comment by rakibtg** [comment]
Are you using version `1.0.3`?

**Comment by rakibtg** [comment]
The `fetch` method will reset the active query; this was an intentional change.
To solve the particular problem as you have stated above, we can introduce a new method like `fetch` but will not reset the active query state. We might call it `shallowFetch` or something like that!
So, i would like to ask you what you think regarding this change?

**Comment by rakibtg** [comment]
Hi @qinst64 i've just implemented `shallowFetch` method that will not reset the active state of the query and will let you update on the existing db object. 
The code looks like this now:
```php
// Find documents.
$result = $usersDB
   ->where('products.totalBought', '>', 0)
   ->where('products.totalSaved', '>', 0);

// Shallow fetch documents so it won't reset the active query state.
$result->shallowFetch();

// Update matched documents.
$result->update([
   'withShallowFetch' => true,
]);
```
I think i will merge the code with master tomorrow after doing some test. 
Also, can you help to name the method that makes more sense instead of calling it `shallowFetch`? :D

**Comment by qinst64** [comment]
Thanks for the response, the naming is fine.
 
I may not investigate deep, Is there any consideration not making it the default behavior?
The `shallowFetch` works like a charm now, yet If there is a case in the future someone asks for a `shallowUpdate`, `shallowInsert`, `shallowDelete`?

**Comment by rakibtg** [comment]
Not resetting the conditions will create more confusions, i think a new method like `keepConditions` would make more sense. Example:
```php
$result->keepConditions()->fetch();
```
Also, i don't think that `shallowInsert` and `shallowDelete` will have any practical use.

**Comment by rakibtg** [comment]
Added `keepConditions` method to keep the conditions of the query.
Example:
```php
   $result = $usersDB
      ->keepConditions()
      ->where('products.totalBought', '>', 50);

   print_r($result->fetch());
   print_r($result->fetch());
```
